export const LIBELLES_LISTE_CONFLITS = {
  vide: 'Aucun conflit de pointage à résoudre.',
  videFiltre: 'Aucun conflit ne correspond à ces filtres.',
  filtrer: 'Filtrer les conflits',
  erreur: 'Impossible de charger les conflits. Réessayez pour obtenir une liste complète.',
  reessayer: 'Réessayer',
  partiel: 'Liste partielle : certains dossiers n’ont pas pu être acquis. Cette sélection ne représente pas tous les conflits.',
  precedente: 'Précédente',
  suivante: 'Suivante',
  pagination: 'Pages des conflits',
  page: 'Page',
  sur: 'sur',
  adresseInvalide: 'Numéro de page invalide. Appliquez les filtres pour revenir à la première page.',
  pageVide: 'Cette page ne contient plus de dossier. D’autres conflits restent dans la sélection.',
  premierePage: 'Revenir à la première page',
  erreurNavigation: 'Impossible d’appliquer les filtres. Réessayez ; la liste acquise reste consultable.',
  operateurNonResolu: 'Opérateur non résolu',
  posteNonResolu: 'Poste non résolu',
} as const;
