import { CategorieDeProduit } from '../../domain/CategorieDeProduit';

export const LIBELLES_ELEMENTS_DE_FABRICATION = {
  titre: 'Produits',
  recherche: 'Rechercher un produit',
  actualiser: 'Actualiser',
  filtrerCategorie: 'Filtrer par catégorie',
  tous: 'Tous',
  aucunResultat: 'Aucun produit ne correspond à cette recherche.',
  sousTitre: 'Créez et tenez à jour les produits de l’atelier, rangés par catégorie.',
  creation: (categorie: CategorieDeProduit): string => `Nouveau produit ${categorie.value}`,
  modification: (numero: string): string => `Modifier ${numero}`,
  miseALAtelier: 'Mettre à l’atelier',
  miseALAtelierDe: (numero: string): string => `Mettre ${numero} à l’atelier`,
  coutDeRevient: 'Coût de revient',
  coutDeRevientDe: (numero: string): string => `Voir le coût de revient de ${numero}`,
  colonnes: {
    categorie: 'Catégorie',
    reference: 'Référence',
    nom: 'Nom',
    libelle: 'Libellé',
    actions: 'Actions',
  },
  tableau: 'Produits de l’atelier',
  referentiel: 'Référentiel des produits',
  defilement: 'Tableau des produits, défilement horizontal disponible',
  chargement: 'Chargement des produits…',
  erreur: 'Impossible de charger les produits. Vérifiez la connexion puis réessayez.',
  reessayer: 'Réessayer',
  vide: 'Aucun produit',
  sansCategorie: 'Aucune catégorie de produit',
  sansCategorieDetails: 'Déclarez d’abord une catégorie de produit : les produits se créent dans une catégorie.',
  videDetails: 'Créez le premier élément de fabrication du référentiel. Son numéro interne sera attribué automatiquement.',
  sansValeur: '—',
  pagination: {
    aria: 'Pagination des produits',
    parPage: 'Éléments par page',
    suivante: 'Page suivante',
    precedente: 'Page précédente',
    premiere: 'Première page',
    derniere: 'Dernière page',
    vide: '0 élément',
    intervalle: (premier: number, dernier: number, total: number): string => `${premier}–${dernier} sur ${total}`,
  },
} as const;

export const LIBELLES_CATEGORIES_DE_PRODUIT = {
  ouvrir: 'Catégories',
  titre: 'Catégories de produit',
  introduction: 'Les produits se créent dans une catégorie. Son code s’affiche tel quel et préfixe le nom des produits.',
  chargement: 'Chargement des catégories…',
  erreur: 'Impossible de charger les catégories. Vérifiez la connexion puis réessayez.',
  reessayer: 'Réessayer',
  vide: 'Aucune catégorie déclarée.',
  liste: 'Catégories, dans l’ordre des boutons de création',
  nouvelle: 'Nouvelle catégorie',
  nouvelleComplement: '(code de 1 à 10 lettres)',
  aideCode: 'Le code ne pourra plus être modifié : il préfixe le nom des produits de la catégorie.',
  declarer: 'Déclarer',
  declaration: 'Déclaration…',
  erreurTechnique: 'La déclaration a échoué. Vérifiez la connexion puis réessayez.',
  fermer: 'Fermer',
} as const;

export const LIBELLES_FORMULAIRE_ELEMENT = {
  introduction: 'Les deux champs sont facultatifs : un produit se réduit légitimement à son seul numéro, attribué automatiquement.',
  reference: 'Référence',
  referenceComplement: '(le numéro de l’entreprise, facultatif)',
  referenceAide: 'Laissez vide si l’entreprise ne donne pas de numéro à cet élément.',
  libelle: 'Libellé',
  libelleComplement: '(une ligne, facultatif)',
  libelleAide: 'Ce qui rend l’élément reconnaissable quand il n’a pas de référence.',
  erreurTechnique: 'L’enregistrement a échoué. Vérifiez la connexion puis réessayez.',
  annuler: 'Annuler',
  enregistrer: 'Enregistrer',
  enregistrement: 'Enregistrement…',
} as const;
