import { CategorieDeProduit } from '../../domain/CategorieDeProduit';

export const LIBELLES_ELEMENTS_DE_FABRICATION = {
  titre: 'Moules et OF',
  recherche: 'Rechercher un moule ou un OF',
  actualiser: 'Actualiser',
  filtrerCategorie: 'Filtrer par catégorie',
  tous: 'Tous',
  aucunResultat: 'Aucun moule ni OF ne correspond à cette recherche.',
  sousTitre: 'Créez et tenez à jour les moules et les OF de l’atelier.',
  creation: (categorie: CategorieDeProduit): string => `Nouveau produit ${categorie.value}`,
  modification: (numero: string): string => `Modifier ${numero}`,
  miseALAtelier: 'Mettre à l’atelier',
  miseALAtelierDe: (numero: string): string => `Mettre ${numero} à l’atelier`,
  coutDeRevient: 'Coût de revient',
  coutDeRevientDe: (numero: string): string => `Voir le coût de revient de ${numero}`,
  colonnes: {
    categorie: 'Catégorie',
    reference: 'Référence',
    nom: 'Nom',
    libelle: 'Libellé',
    actions: 'Actions',
  },
  tableau: 'Moules et OF de l’atelier',
  referentiel: 'Référentiel des moules et des OF',
  defilement: 'Tableau des moules et OF, défilement horizontal disponible',
  chargement: 'Chargement des moules et OF…',
  erreur: 'Impossible de charger les moules et OF. Vérifiez la connexion puis réessayez.',
  reessayer: 'Réessayer',
  vide: 'Aucun moule ni OF',
  videDetails: 'Créez le premier élément de fabrication du référentiel. Son numéro interne sera attribué automatiquement.',
  sansValeur: '—',
  pagination: {
    aria: 'Pagination des moules et OF',
    parPage: 'Éléments par page',
    suivante: 'Page suivante',
    precedente: 'Page précédente',
    premiere: 'Première page',
    derniere: 'Dernière page',
    vide: '0 élément',
    intervalle: (premier: number, dernier: number, total: number): string => `${premier}–${dernier} sur ${total}`,
  },
} as const;

export const LIBELLES_FORMULAIRE_ELEMENT = {
  introduction: 'Les deux champs sont facultatifs : un produit se réduit légitimement à son seul numéro, attribué automatiquement.',
  reference: 'Référence',
  referenceComplement: '(le numéro de l’entreprise, facultatif)',
  referenceAide: 'Laissez vide si l’entreprise ne donne pas de numéro à cet élément.',
  libelle: 'Libellé',
  libelleComplement: '(une ligne, facultatif)',
  libelleAide: 'Ce qui rend l’élément reconnaissable quand il n’a pas de référence.',
  erreurTechnique: 'L’enregistrement a échoué. Vérifiez la connexion puis réessayez.',
  annuler: 'Annuler',
  enregistrer: 'Enregistrer',
  enregistrement: 'Enregistrement…',
} as const;
