/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/atelier/journees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lister les journees de travail
     * @description Filtres facultatifs. La periode, quand elle est fournie, porte sur l'heure d'arrivee.
     */
    get: operations['list_4'];
    put?: never;
    /**
     * Enregistrer une arrivee
     * @description Ouvre la journee de travail de l'operateur.
     *
     *     Sans dateDeSurvenue, l'arrivee est datee a l'instant present : c'est le geste du matin. Avec, c'est le
     *     gestionnaire qui saisit apres coup une arrivee jamais pointee.
     */
    post: operations['arrive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/journees/pointages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pointer une pause, une reprise ou un depart
     * @description Vise la journee ouverte de l'operateur, retrouvee par le serveur : aucun identifiant de journee n'est a fournir.
     *
     *     Un seul appel, quel que soit le nombre d'elements en cours. Ne jamais boucler sur les elements pour repercuter une
     *     pause : le croisement est fait a la lecture du temps effectif.
     */
    post: operations['pointe_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/journees/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consulter une journee de travail
     * @description Expose a la fois l'amplitude et les fenetres : le contexte ne choisit pas laquelle compte pour la paie.
     */
    get: operations['get_5'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/journees/{id}/evenements/{evenementId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Corriger une presence fausse
     * @description Une annulation et une regularisation en un seul appel.
     */
    put: operations['corrige_1'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/journees/{id}/evenements/{evenementId}/annulation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Annuler une presence saisie en trop
     * @description L'evenement reste au journal, porteur de son annulation.
     */
    post: operations['annule_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/journees/{id}/regularisations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rattraper une presence oubliee
     * @description Le cas type : l'operateur est rentre chez lui sans pointer son depart, et le gestionnaire le saisit le lendemain a
     *     l'heure reelle. Cette seule regularisation referme aussi tous les elements restes ouverts.
     */
    post: operations['regularise_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lister les elements engages
     * @description Le tableau de l'atelier.
     *
     *     Tous les filtres sont facultatifs : l'ecran des operateurs veut tous les elements actifs d'un coup, sans notion de
     *     date. Le parametre etats accepte plusieurs valeurs (?etats=EN_ATTENTE&etats=EN_COURS) ; absent, il ne filtre rien.
     *     La periode, quand elle est fournie, porte sur la date d'engagement.
     */
    get: operations['list_3'];
    put?: never;
    /**
     * Engager un element en atelier
     * @description Geste metier du back-office, distinct de la creation de l'element : tout ce qui est cree n'est pas forcement a
     *     faire, et c'est cet acte qui fait apparaitre l'element sur l'ecran des operateurs.
     *
     *     Le nom et le type de l'element sont copies a cet instant ; l'atelier ne les relira plus.
     */
    post: operations['engage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un element engage */
    get: operations['get_4'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}/cloture': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cloturer un element, ou deplacer sa cloture
     * @description La cloture ne fige rien pour le gestionnaire : regularisation, annulation et correction restent possibles ensuite.
     *     Rappelee sur un element deja cloture, cette route deplace la date de cloture.
     */
    put: operations['cloture'];
    post?: never;
    /**
     * Rouvrir un element cloture
     * @description Retire la cloture. L'element redevient pointable.
     */
    delete: operations['annuleLaCloture'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}/evenements/{evenementId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Corriger une saisie fausse
     * @description Troisieme acte : une annulation et une regularisation en un seul appel.
     */
    put: operations['corrige'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}/evenements/{evenementId}/annulation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Annuler une saisie en trop
     * @description Deuxieme acte de correction. L'evenement reste au journal.
     */
    post: operations['annule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}/pointages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pointer un debut, une non conformite ou une fin
     * @description Le geste de l'operateur, date a l'instant present.
     *
     *     Ne jamais pointer ici une pause ou un depart : ce sont des faits de la journee de travail de l'operateur, ecrits
     *     une seule fois via POST /api/atelier/journees/pointages.
     */
    post: operations['pointe'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}/regularisations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rattraper une saisie oubliee
     * @description Premier des trois actes de correction.
     */
    post: operations['regularise'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/atelier/suivis/{id}/temps-effectif': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lire le temps effectivement passe sur un element
     * @description Les intervalles bruts du journal, ramenes aux fenetres de presence des operateurs.
     *
     *     C'est ici que la pause de midi scinde un travail en deux et qu'un depart referme ce que l'operateur a oublie
     *     d'arreter, sans qu'aucun de ces faits ait eu besoin d'etre recopie dans le journal de l'element. Un intervalle
     *     sans fin est encore en cours.
     */
    get: operations['tempsEffectif'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/elements-de-fabrication': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_2'];
    put?: never;
    post: operations['create_2'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/elements-de-fabrication/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_2'];
    put: operations['update_2'];
    post?: never;
    delete: operations['delete_2'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/feuilles-de-temps/{operateurId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lire la feuille de temps hebdomadaire d'un operateur
     * @description Rend les sept jours de la semaine ISO demandee, chacun portant les fenetres de presence qui lui reviennent dans
     *     le fuseau horaire de l'entreprise.
     *
     *     La semaine est toujours explicite : aucune semaine courante implicite, pour que deux appels identiques rendent
     *     toujours la meme chose. L'annee est celle des semaines ISO, qui differe de l'annee civile a ses bornes — la
     *     semaine 1 de 2026 commence le 29 decembre 2025.
     */
    get: operations['get_3'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operateurs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lister les operateurs
     * @description La page demandee, triee par nom puis prenom. Le filtre sur le poste repond a la question du pupitre : qui est
     *     habilite sur ce poste ? Absent, il ne filtre rien.
     */
    get: operations['list_1'];
    put?: never;
    /** Declarer un operateur */
    post: operations['create_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operateurs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un operateur */
    get: operations['get_1'];
    /**
     * Reviser un operateur
     * @description La liste de postes fournie remplace la precedente ; un matricule laisse vide est retire.
     */
    put: operations['update_1'];
    post?: never;
    /** Supprimer un operateur */
    delete: operations['delete_1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/postes-de-travail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lister les postes de travail
     * @description La page demandee, triee par libelle. Le filtre sur la nature est facultatif ; absent, il ne filtre rien.
     */
    get: operations['list'];
    put?: never;
    /** Declarer un poste de travail */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/postes-de-travail/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un poste de travail */
    get: operations['get'];
    /**
     * Reviser un poste de travail
     * @description Le poste renomme s'affiche renomme partout : rien n'en est copie sur les operateurs, qui n'en retiennent que
     *     l'identifiant.
     */
    put: operations['update'];
    post?: never;
    /**
     * Supprimer un poste de travail
     * @description Refuse tant qu'un operateur y est habilite : le supprimer le laisserait pointer sur du vide. Le retirer de leurs
     *     habilitations d'abord.
     */
    delete: operations['delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PageRestElementDeFabrication: {
      content?: components['schemas']['RestElementDeFabrication'][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int64 */
      totalElementsCount?: number;
    };
    PageRestJourneeDeTravail: {
      content?: components['schemas']['RestJourneeDeTravail'][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int64 */
      totalElementsCount?: number;
    };
    PageRestOperateur: {
      content?: components['schemas']['RestOperateur'][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int64 */
      totalElementsCount?: number;
    };
    PageRestPosteDeTravail: {
      content?: components['schemas']['RestPosteDeTravail'][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int64 */
      totalElementsCount?: number;
    };
    PageRestSuiviDAtelier: {
      content?: components['schemas']['RestSuiviDAtelier'][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int64 */
      totalElementsCount?: number;
    };
    /** @description Ce que l'ecran d'atelier affiche : qui fait quoi, dans quel etat, depuis quand. */
    RestActiviteEnCours: {
      /**
       * @description TRAVAIL ou NON_CONFORMITE.
       * @enum {string}
       */
      categorie?: 'TRAVAIL' | 'NON_CONFORMITE';
      /**
       * Format: date-time
       * @description Instant depuis lequel cette activite dure.
       */
      depuis?: string;
      /** @description Operateur en activite. */
      operateur?: components['schemas']['RestOperateur'];
      /** @description Poste de travail, facultatif. */
      poste?: components['schemas']['RestPosteDeTravail'];
    };
    /** @description L'annulation d'un evenement. L'evenement reste au journal, porteur de cette annulation. */
    RestAnnulation: {
      /**
       * @description Utilisateur ayant annule l'evenement.
       * @example gestionnaire.impeccmold
       */
      auteur?: string;
      /**
       * Format: date-time
       * @description Instant auquel l'annulation a ete saisie.
       */
      date?: string;
      /**
       * @description Motif saisi par le gestionnaire.
       * @example Erreur de saisie
       */
      motif?: string;
    };
    /**
     * @description L'annulation d'une saisie en trop.
     *
     *     L'evenement n'est pas supprime : il reste au journal, porteur de son annulation, et le repli l'ecarte.
     */
    RestAnnulationDEvenement: {
      /**
       * @description Motif de l'annulation.
       * @example Erreur de saisie
       */
      motif: string;
    };
    /**
     * @description L'arrivee, qui ouvre la journee de travail d'un operateur.
     *
     *     L'operateur qui s'identifie le matin et le gestionnaire qui saisit apres coup une arrivee jamais pointee passent par
     *     le meme acte : seule `dateDeSurvenue` change.
     */
    RestArrivee: {
      /**
       * Format: date-time
       * @description Heure metier de l'arrivee. Absente, elle vaut l'instant present.
       */
      dateDeSurvenue?: string;
      /**
       * Format: uuid
       * @description Identifiant de l'operateur qui arrive.
       */
      operateur: string;
    };
    /**
     * @description La cloture d'un element engage.
     *
     *     Elle ne fige rien pour le gestionnaire : regularisation, annulation et correction restent possibles ensuite, et la
     *     cloture elle-meme peut etre deplacee ou annulee.
     */
    RestCloture: {
      /**
       * Format: date-time
       * @description Heure metier de la cloture. Absente, elle vaut l'instant present.
       */
      dateDeSurvenue?: string;
    };
    /**
     * @description La correction d'une saisie fausse : une annulation et une regularisation jouees en un seul acte.
     *
     *     L'evenement d'origine reste au journal, annule, et le remplacant y prend sa place a l'heure corrigee.
     */
    RestCorrection: {
      /**
       * Format: date-time
       * @description Heure metier corrigee.
       */
      dateDeSurvenue: string;
      /**
       * @description Motif de l'annulation de la saisie fausse.
       * @example Heure erronee
       */
      motif: string;
      /**
       * Format: uuid
       * @description Identifiant de l'operateur dont le temps est affecte.
       */
      operateur: string;
      /**
       * Format: uuid
       * @description Identifiant du poste de travail, facultatif.
       */
      poste?: string;
      /**
       * @description Nature du pointage corrige.
       * @enum {string}
       */
      type: 'DEBUT' | 'NON_CONFORMITE' | 'FIN';
    };
    /** @description La correction d'une presence fausse : une annulation et une regularisation en un seul acte. */
    RestCorrectionDePresence: {
      /**
       * Format: date-time
       * @description Heure metier corrigee.
       */
      dateDeSurvenue: string;
      /**
       * @description Motif de l'annulation.
       * @example Heure erronee
       */
      motif: string;
      /**
       * @description Nature du pointage corrige.
       * @enum {string}
       */
      type: 'ARRIVEE' | 'PAUSE' | 'REPRISE' | 'DEPART';
    };
    RestCreationElementDeFabrication: {
      description?: string;
      reference?: string;
      /** @enum {string} */
      type: 'ORDRE_DE_FABRICATION' | 'PRODUIT';
    };
    /** @description Declaration d'un operateur. */
    RestCreationOperateur: {
      /**
       * @description Matricule interne. Facultatif : toutes les entreprises n'en attribuent pas. Unique des qu'il est renseigne.
       * @example 049
       */
      matricule?: string;
      /**
       * @description Nom de famille.
       * @example Dupont
       */
      nom: string;
      /** @description Identifiants des postes sur lesquels l'operateur est habilite. Ce sont eux qui disent ses metiers. */
      postes?: string[];
      /**
       * @description Prenom.
       * @example Jean
       */
      prenom: string;
      /**
       * @description Taux horaire de l'operateur, destine au cout de revient. Facultatif : toutes les entreprises ne le valorisent pas.
       * @example 22
       */
      tauxHoraire?: number;
    };
    /** @description Declaration d'un poste de travail. */
    RestCreationPosteDeTravail: {
      /**
       * @description Cout horaire du poste, destine au cout de revient. Facultatif : toutes les entreprises ne le valorisent pas.
       * @example 45.5
       */
      coutHoraire?: number;
      /**
       * @description Nom du poste, unique dans l'entreprise.
       * @example Tour 1
       */
      libelle: string;
      /**
       * @description Metier qui s'exerce sur ce poste. Obligatoire : un poste est declare pour dire quel travail s'y fait.
       * @example tournage
       */
      nature: string;
    };
    RestElementDeFabrication: {
      /** Format: date-time */
      dateDeCreation?: string;
      /** Format: date-time */
      dateDeModification?: string;
      description?: string;
      /** Format: uuid */
      id?: string;
      nom?: string;
      reference?: string;
      /** @enum {string} */
      type?: 'ORDRE_DE_FABRICATION' | 'PRODUIT';
    };
    /** @description Mise d'un element de fabrication en atelier. */
    RestEngagement: {
      /**
       * Format: uuid
       * @description Identifiant de l'element de fabrication a engager.
       */
      element: string;
    };
    /**
     * @description Un evenement du journal d'un element engage.
     *
     *     Comme pour la presence, l'horodatage est bitemporel. La pause et le depart de l'operateur **ne figurent jamais ici** :
     *     ce sont des faits de sa journee de travail, croises a la lecture.
     */
    RestEvenementDAtelier: {
      /** @description Presente lorsque l'evenement a ete annule. L'evenement reste au journal. */
      annulation?: components['schemas']['RestAnnulation'];
      /**
       * @description Utilisateur ayant saisi l'evenement.
       * @example dupont
       */
      auteur?: string;
      /**
       * @description Cout horaire du poste, copie a la saisie. Absent si le poste n'est pas valorise ou si aucun poste n'est fourni.
       * @example 45.5
       */
      coutHoraire?: number;
      /**
       * Format: date-time
       * @description Heure a laquelle la saisie a ete enregistree.
       */
      dateDEnregistrement?: string;
      /**
       * Format: date-time
       * @description Heure metier a laquelle le fait a eu lieu.
       */
      dateDeSurvenue?: string;
      /** @description Vrai lorsque la saisie a ete faite apres coup. */
      estUneRegularisation?: boolean;
      /**
       * Format: uuid
       * @description Identifiant de l'evenement, a reprendre pour l'annuler ou le corriger.
       */
      id?: string;
      /** @description Nature de l'operation, recopiee du poste a la saisie. Simple axe d'agregation. */
      nature?: string;
      /** @description Operateur dont le temps est affecte. */
      operateur?: components['schemas']['RestOperateur'];
      /** @description Poste de travail, toujours facultatif. */
      poste?: components['schemas']['RestPosteDeTravail'];
      /**
       * @description Taux horaire de l'operateur, copie a la saisie. Absent si l'operateur n'est pas valorise.
       * @example 22
       */
      tauxHoraire?: number;
      /**
       * @description Nature du pointage. Une reprise apres non conformite se pointe comme un DEBUT.
       * @enum {string}
       */
      type?: 'DEBUT' | 'NON_CONFORMITE' | 'FIN';
    };
    /**
     * @description Un evenement du journal de presence.
     *
     *     L'horodatage est **bitemporel** : `dateDeSurvenue` est l'heure metier, `dateDEnregistrement` l'heure de la saisie.
     *     Une regularisation se reconnait a l'ecart entre les deux (`estUneRegularisation`), jamais a l'identite de l'auteur.
     */
    RestEvenementDePresence: {
      /** @description Presente lorsque l'evenement a ete annule. L'evenement reste au journal. */
      annulation?: components['schemas']['RestAnnulation'];
      /**
       * @description Utilisateur ayant saisi l'evenement.
       * @example user.impeccmold
       */
      auteur?: string;
      /**
       * Format: date-time
       * @description Heure a laquelle la saisie a ete enregistree.
       */
      dateDEnregistrement?: string;
      /**
       * Format: date-time
       * @description Heure metier a laquelle le fait a eu lieu.
       */
      dateDeSurvenue?: string;
      /** @description Vrai lorsque la saisie a ete faite apres coup. */
      estUneRegularisation?: boolean;
      /**
       * Format: uuid
       * @description Identifiant de l'evenement, a reprendre pour l'annuler ou le corriger.
       */
      id?: string;
      /**
       * @description Nature du pointage.
       * @enum {string}
       */
      type?: 'ARRIVEE' | 'PAUSE' | 'REPRISE' | 'DEPART';
    };
    /**
     * @description Un intervalle pendant lequel l'operateur etait present et non en pause.
     *
     *     C'est la matiere du temps effectif : une pause de midi scinde la journee en deux fenetres, un depart referme la
     *     derniere. Une fenetre sans `fin` est encore ouverte.
     */
    RestFenetreDePresence: {
      /**
       * Format: date-time
       * @description Debut de la fenetre.
       */
      debut?: string;
      /**
       * Format: date-time
       * @description Fin de la fenetre, absente si l'operateur est toujours present.
       */
      fin?: string;
    };
    /**
     * @description L'historique calendaire d'un operateur sur une semaine ISO.
     *
     *     Rien n'est stocke : la feuille est recalculee a chaque lecture depuis les journaux de l'atelier, pour qu'une saisie
     *     regularisee apres coup compte a l'heure ou le travail a eu lieu.
     */
    RestFeuilleDeTemps: {
      /**
       * Format: int32
       * @description Annee ISO de la semaine. Attention, elle differe de l'annee civile aux changements d'annee.
       * @example 2026
       */
      annee?: number;
      /** @description Les sept jours, du lundi au dimanche. */
      jours?: components['schemas']['RestJourDeLaSemaine'][];
      /** @description L'operateur, resolu au referentiel. */
      operateur?: components['schemas']['RestOperateur'];
      /**
       * Format: int32
       * @description Numero de la semaine ISO.
       * @example 20
       */
      semaine?: number;
    };
    /**
     * @description Du temps passe sur un element, deduit du journal et jamais stocke.
     *
     *     Le temps effectif est l'intersection des intervalles bruts avec les fenetres de presence de l'operateur : c'est
     *     pourquoi une pause de midi produit deux intervalles la ou l'operateur n'a pointe qu'un debut.
     */
    RestIntervalleDActivite: {
      /**
       * @description TRAVAIL ou NON_CONFORMITE.
       * @enum {string}
       */
      categorie?: 'TRAVAIL' | 'NON_CONFORMITE';
      /**
       * Format: date-time
       * @description Debut de l'intervalle.
       */
      debut?: string;
      /**
       * Format: uuid
       * @description Evenement qui a ouvert l'intervalle.
       */
      evenement?: string;
      /**
       * Format: date-time
       * @description Fin de l'intervalle, absente s'il est encore en cours.
       */
      fin?: string;
      /** @description Nature de l'operation, facultative. */
      nature?: string;
      /** @description Operateur concerne. */
      operateur?: components['schemas']['RestOperateur'];
      /** @description Poste de travail, facultatif. */
      poste?: components['schemas']['RestPosteDeTravail'];
    };
    /**
     * @description Un jour du calendrier de l'entreprise, et la presence qui lui revient.
     *
     *     Les sept jours sont toujours rendus, meme vides : un trou obligerait le lecteur a deviner s'il manque une journee
     *     ou si l'operateur n'etait pas la.
     */
    RestJourDeLaSemaine: {
      /**
       * Format: date
       * @description Date du jour, dans le fuseau de l'entreprise.
       * @example 2026-05-11
       */
      jour?: string;
      /** @description Fenetres de presence de ce jour, dans l'ordre des heures. */
      presence?: components['schemas']['RestPlage'][];
    };
    /**
     * @description La journee de travail d'un operateur : une venue, bornee par une arrivee et un depart.
     *
     *     Ce n'est **pas** un jour calendaire — le contexte ne connait ni fuseau horaire ni date. L'API expose a la fois
     *     `amplitude` (de l'arrivee au depart) et `fenetres` (pauses retirees) sans choisir laquelle compte pour la paie.
     */
    RestJourneeDeTravail: {
      /** @description De l'arrivee au depart, pauses comprises. Absente tant que la journee est ouverte. */
      amplitude?: components['schemas']['RestPeriode'];
      /**
       * @description ABSENT, PRESENT ou EN_PAUSE. Deduit du journal.
       * @enum {string}
       */
      etat?: 'ABSENT' | 'PRESENT' | 'EN_PAUSE';
      /** @description Les intervalles de presence effective, pauses retirees. */
      fenetres?: components['schemas']['RestFenetreDePresence'][];
      /**
       * Format: uuid
       * @description Identifiant de la journee.
       */
      id?: string;
      /** @description Le journal complet, annules compris, du plus ancien au plus recent. */
      journal?: components['schemas']['RestEvenementDePresence'][];
      /** @description Operateur concerne. */
      operateur?: components['schemas']['RestOperateur'];
    };
    RestModificationElementDeFabrication: {
      description?: string;
      reference?: string;
    };
    /** @description Revision d'un operateur. */
    RestModificationOperateur: {
      /**
       * @description Matricule interne, laisse vide pour le retirer.
       * @example 049
       */
      matricule?: string;
      /**
       * @description Nom de famille.
       * @example Dupont
       */
      nom: string;
      /** @description Identifiants des postes habilites. La liste fournie remplace la precedente. */
      postes?: string[];
      /**
       * @description Prenom.
       * @example Jean
       */
      prenom: string;
      /**
       * @description Taux horaire de l'operateur, laisse vide pour le retirer.
       * @example 22
       */
      tauxHoraire?: number;
    };
    /** @description Revision d'un poste de travail. */
    RestModificationPosteDeTravail: {
      /**
       * @description Cout horaire du poste, laisse vide pour le retirer.
       * @example 45.5
       */
      coutHoraire?: number;
      /**
       * @description Nom du poste, unique dans l'entreprise.
       * @example Tour 1
       */
      libelle: string;
      /**
       * @description Metier qui s'exerce sur ce poste.
       * @example tournage
       */
      nature: string;
    };
    /** @description Un operateur et les postes sur lesquels il est habilite. */
    RestOperateur: {
      /**
       * Format: uuid
       * @description Identifiant de l'operateur.
       */
      id: string;
      /**
       * @description Matricule interne, absent si l'entreprise n'en attribue pas.
       * @example 049
       */
      matricule?: string;
      /**
       * @description Metiers de l'operateur, deduits des natures de ses postes. Jamais saisis.
       * @example [
       *       "soudage",
       *       "tournage"
       *     ]
       */
      natures?: string[];
      /**
       * @description Nom de famille.
       * @example Dupont
       */
      nom: string;
      /** @description Postes habilites, tries par libelle. */
      postes?: components['schemas']['RestPosteHabilite'][];
      /**
       * @description Prenom.
       * @example Jean
       */
      prenom: string;
      /**
       * @description Taux horaire de l'operateur, absent si l'entreprise ne le valorise pas.
       * @example 22
       */
      tauxHoraire?: number;
    };
    /** @description Un intervalle de temps borne a ses deux extremites. */
    RestPeriode: {
      /**
       * Format: date-time
       * @description Debut inclus.
       */
      debut?: string;
      /**
       * Format: date-time
       * @description Fin incluse.
       */
      fin?: string;
    };
    /**
     * @description Un intervalle de presence, deja ramene au jour qui le porte.
     *
     *     Une plage sans fin n'est pas une anomalie : l'operateur n'a pas encore pointe son depart.
     */
    RestPlage: {
      /**
       * Format: date-time
       * @description Debut de la plage.
       * @example 2026-05-11T06:00:00Z
       */
      debut?: string;
      /**
       * Format: date-time
       * @description Fin de la plage, absente tant que l'operateur n'est pas parti.
       */
      fin?: string;
    };
    /** @description Un pointage de l'operateur sur un element engage, date a l'instant present. */
    RestPointage: {
      /**
       * Format: uuid
       * @description Identifiant de l'operateur dont le temps est affecte.
       */
      operateur: string;
      /**
       * Format: uuid
       * @description Identifiant du poste de travail. Toujours facultatif : une entreprise sans parc machine le laisse vide.
       */
      poste?: string;
      /**
       * @description DEBUT, NON_CONFORMITE ou FIN. Une reprise apres non conformite se pointe comme un DEBUT.
       * @enum {string}
       */
      type: 'DEBUT' | 'NON_CONFORMITE' | 'FIN';
    };
    /**
     * @description Une pause, une reprise ou un depart, saisis en direct sur la journee ouverte de l'operateur.
     *
     *     Un seul evenement, quel que soit le nombre d'elements sur lesquels l'operateur travaille : c'est ce qui donne un
     *     bouton de pause unique, sans N clics pour N taches. Aucun identifiant de journee n'est necessaire.
     */
    RestPointageDePresence: {
      /**
       * Format: uuid
       * @description Identifiant de l'operateur qui pointe.
       */
      operateur: string;
      /**
       * @description PAUSE, REPRISE ou DEPART. ARRIVEE passe par POST /api/atelier/journees.
       * @enum {string}
       */
      type: 'ARRIVEE' | 'PAUSE' | 'REPRISE' | 'DEPART';
    };
    /** @description Un poste de travail du referentiel de l'entreprise. */
    RestPosteDeTravail: {
      /**
       * @description Cout horaire du poste, absent si l'entreprise ne le valorise pas.
       * @example 45.5
       */
      coutHoraire?: number;
      /**
       * Format: uuid
       * @description Identifiant du poste.
       */
      id: string;
      /**
       * @description Nom du poste tel que l'atelier le designe.
       * @example Tour 1
       */
      libelle: string;
      /**
       * @description Metier qui s'exerce sur ce poste.
       * @example tournage
       */
      nature: string;
    };
    /** @description Un poste sur lequel l'operateur est habilite, resolu au moment de la lecture. */
    RestPosteHabilite: {
      /**
       * Format: uuid
       * @description Identifiant du poste.
       */
      id: string;
      /**
       * @description Nom du poste.
       * @example Tour 1
       */
      libelle: string;
      /**
       * @description Metier qui s'exerce sur ce poste.
       * @example tournage
       */
      nature: string;
    };
    /**
     * @description Une saisie oubliee, rattrapee par le gestionnaire a l'heure ou elle a reellement eu lieu.
     *
     *     L'evenement produit portera `dateDeSurvenue` (fournie ici) et `dateDEnregistrement` (l'instant courant) : c'est cet
     *     ecart, et lui seul, qui signale une regularisation.
     */
    RestRegularisation: {
      /**
       * Format: date-time
       * @description Heure metier a laquelle le fait a reellement eu lieu.
       */
      dateDeSurvenue: string;
      /**
       * Format: uuid
       * @description Identifiant de l'operateur dont le temps est affecte.
       */
      operateur: string;
      /**
       * Format: uuid
       * @description Identifiant du poste de travail, facultatif.
       */
      poste?: string;
      /**
       * @description Nature du pointage rattrape.
       * @enum {string}
       */
      type: 'DEBUT' | 'NON_CONFORMITE' | 'FIN';
    };
    /**
     * @description Une presence rattrapee par le gestionnaire, sur une journee deja ouverte, a l'heure ou elle a reellement eu lieu.
     *
     *     Une seule regularisation de depart suffit a refermer tous les elements restes ouverts ce jour-la : le correctif est
     *     porte par la presence, jamais recopie element par element.
     */
    RestRegularisationDePresence: {
      /**
       * Format: date-time
       * @description Heure metier a laquelle le fait a reellement eu lieu.
       */
      dateDeSurvenue: string;
      /**
       * @description Nature du pointage rattrape.
       * @enum {string}
       */
      type: 'ARRIVEE' | 'PAUSE' | 'REPRISE' | 'DEPART';
    };
    /**
     * @description Le suivi en atelier d'un element engage.
     *
     *     Son etat, ses activites en cours et son temps ne sont **jamais stockes** : tout est deduit du journal a chaque
     *     lecture. C'est ce qui permet a une saisie rattrapee de compter a l'heure ou elle a reellement eu lieu.
     */
    RestSuiviDAtelier: {
      /** @description Les activites ouvertes a cet instant. */
      activitesEnCours?: components['schemas']['RestActiviteEnCours'][];
      /**
       * Format: date-time
       * @description Instant metier de la cloture, absent tant que l'element n'est pas cloture.
       */
      clotureLe?: string;
      /** @description Utilisateur ayant cloture l'element, absent tant qu'il ne l'est pas. */
      cloturePar?: string;
      /**
       * Format: uuid
       * @description Identifiant de l'element de fabrication engage.
       */
      element?: string;
      /**
       * Format: date-time
       * @description Instant de l'engagement.
       */
      engageLe?: string;
      /**
       * @description Utilisateur ayant engage l'element.
       * @example gestionnaire.impeccmold
       */
      engagePar?: string;
      /**
       * @description EN_ATTENTE, EN_COURS, INTERROMPU ou CLOTURE. Deduit du journal.
       * @enum {string}
       */
      etat?: 'EN_ATTENTE' | 'EN_COURS' | 'INTERROMPU' | 'CLOTURE';
      /**
       * Format: uuid
       * @description Identifiant du suivi. C'est lui, et non celui de l'element, que portent les URLs.
       */
      id?: string;
      /** @description Le journal complet, annules compris, du plus ancien au plus recent. */
      journal?: components['schemas']['RestEvenementDAtelier'][];
      /**
       * @description Nom de l'element, copie a l'engagement.
       * @example OF-2026-000042
       */
      nom?: string;
      /**
       * @description Type de l'element, copie a l'engagement.
       * @enum {string}
       */
      type?: 'ORDRE_DE_FABRICATION' | 'PRODUIT';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_4: {
    parameters: {
      query?: {
        debut?: string;
        fin?: string;
        operateur?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La page demandee, triee par debut descendant. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageRestJourneeDeTravail'];
        };
      };
    };
  };
  arrive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestArrivee'];
      };
    };
    responses: {
      /** @description La journee est ouverte. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Aucun operateur ne porte cet identifiant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Cet operateur a deja une journee ouverte. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
    };
  };
  pointe_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestPointageDePresence'];
      };
    };
    responses: {
      /** @description Le pointage est enregistre. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Cet operateur n'a aucune journee ouverte. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Transition impossible depuis l'etat de presence courant. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
    };
  };
  get_5: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Journee introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
    };
  };
  corrige_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        evenementId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestCorrectionDePresence'];
      };
    };
    responses: {
      /** @description Journee ou evenement introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Evenement deja annule, ou transition impossible. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
    };
  };
  annule_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        evenementId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestAnnulationDEvenement'];
      };
    };
    responses: {
      /** @description Journee ou evenement introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Evenement deja annule. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
    };
  };
  regularise_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestRegularisationDePresence'];
      };
    };
    responses: {
      /** @description La regularisation est enregistree. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Journee introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
      /** @description Transition impossible depuis l'etat de presence a cet instant. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestJourneeDeTravail'];
        };
      };
    };
  };
  list_3: {
    parameters: {
      query?: {
        debut?: string;
        fin?: string;
        etats?: ('EN_ATTENTE' | 'EN_COURS' | 'INTERROMPU' | 'CLOTURE')[];
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La page demandee, triee par date d'engagement descendante. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageRestSuiviDAtelier'];
        };
      };
    };
  };
  engage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestEngagement'];
      };
    };
    responses: {
      /** @description L'element est engage. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Aucun element de fabrication ne porte cet identifiant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Cet element est deja engage et non cloture. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  get_4: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Suivi introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  cloture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestCloture'];
      };
    };
    responses: {
      /** @description Suivi introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Le journal porte un evenement posterieur a la date de cloture demandee. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  annuleLaCloture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Suivi introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  corrige: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        evenementId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestCorrection'];
      };
    };
    responses: {
      /** @description Suivi, evenement, operateur ou poste de travail introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Operateur non habilite sur ce poste, evenement deja annule, ou transition impossible. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  annule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        evenementId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestAnnulationDEvenement'];
      };
    };
    responses: {
      /** @description Suivi ou evenement introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Evenement deja annule. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  pointe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestPointage'];
      };
    };
    responses: {
      /** @description Le pointage est enregistre. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Suivi, operateur ou poste de travail introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Operateur non habilite sur ce poste, element cloture, ou transition impossible depuis l'etat courant. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  regularise: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestRegularisation'];
      };
    };
    responses: {
      /** @description La regularisation est enregistree. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Suivi, operateur ou poste de travail introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
      /** @description Operateur non habilite sur ce poste, transition impossible, ou evenement anterieur a l'engagement. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestSuiviDAtelier'];
        };
      };
    };
  };
  tempsEffectif: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Suivi introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestIntervalleDActivite'][];
        };
      };
    };
  };
  list_2: {
    parameters: {
      query: {
        debut: string;
        fin: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageRestElementDeFabrication'];
        };
      };
    };
  };
  create_2: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestCreationElementDeFabrication'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestElementDeFabrication'];
        };
      };
    };
  };
  get_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestElementDeFabrication'];
        };
      };
    };
  };
  update_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestModificationElementDeFabrication'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestElementDeFabrication'];
        };
      };
    };
  };
  delete_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_3: {
    parameters: {
      query: {
        /**
         * @description Annee ISO de la semaine.
         * @example 2026
         */
        annee: number;
        /**
         * @description Numero de la semaine ISO.
         * @example 20
         */
        semaine: number;
      };
      header?: never;
      path: {
        /** @description Identifiant de l'operateur dans le referentiel. */
        operateurId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La feuille de temps de la semaine demandee. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestFeuilleDeTemps'];
        };
      };
      /** @description Annee ou numero de semaine hors bornes. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestFeuilleDeTemps'];
        };
      };
      /** @description Operateur inconnu du referentiel. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestFeuilleDeTemps'];
        };
      };
    };
  };
  list_1: {
    parameters: {
      query?: {
        poste?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La page demandee, triee par nom puis prenom. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageRestOperateur'];
        };
      };
    };
  };
  create_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestCreationOperateur'];
      };
    };
    responses: {
      /** @description L'operateur est declare. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestOperateur'];
        };
      };
      /** @description Un des postes references est introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestOperateur'];
        };
      };
      /** @description Cette identite ou ce matricule appartient deja a un autre operateur. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestOperateur'];
        };
      };
    };
  };
  get_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operateur introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestOperateur'];
        };
      };
    };
  };
  update_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestModificationOperateur'];
      };
    };
    responses: {
      /** @description Operateur ou poste reference introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestOperateur'];
        };
      };
      /** @description Cette identite ou ce matricule appartient deja a un autre operateur. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestOperateur'];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description L'operateur est supprime. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Operateur introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Du temps est pointe au nom de cet operateur. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list: {
    parameters: {
      query?: {
        nature?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La page demandee, triee par libelle. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageRestPosteDeTravail'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestCreationPosteDeTravail'];
      };
    };
    responses: {
      /** @description Le poste est declare. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestPosteDeTravail'];
        };
      };
      /** @description Un autre poste porte deja ce libelle. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestPosteDeTravail'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Poste de travail introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestPosteDeTravail'];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestModificationPosteDeTravail'];
      };
    };
    responses: {
      /** @description Poste de travail introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestPosteDeTravail'];
        };
      };
      /** @description Un autre poste porte deja ce libelle. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RestPosteDeTravail'];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Le poste est supprime. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Poste de travail introuvable. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Des operateurs sont encore habilites sur ce poste, ou du temps y a deja ete pointe. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
