const ERREURS_SAISIE: Readonly<Record<string, string>> = {
  ACTE_REQUIS: 'Choisissez un acte.',
  MOTIF_REQUIS: 'Renseignez un motif.',
  MOTIF_INVALIDE: 'Le motif doit contenir de 1 à 255 caractères.',
  OPERATEUR_REQUIS: 'Renseignez l’opérateur.',
  CIBLE_REQUISE: 'Choisissez l’activité visée.',
  CIBLE_INTERDITE: 'Une ouverture ne vise aucune activité ; effacez explicitement la cible.',
  INSTANT_INVALIDE: 'Renseignez une date et heure ISO avec son fuseau.',
  INTENTION_INCOMPATIBLE: 'Le type et l’intention ne sont pas compatibles.',
  TYPE_REQUIS: 'Choisissez le type du pointage.',
  INTENTION_REQUISE: 'Choisissez son intention.',
};

export const LIBELLES_CONFLITS = {
  reinitialiser: 'Réinitialiser la démonstration',
  erreurReset: 'Impossible de réinitialiser la démonstration. Réessayez.',
  detail: 'Un pointage manque dans la chronologie ?',
  pourquoi: 'Pourquoi ces pointages sont incohérents',
  tracabilite: 'Voir les détails et l’enregistrement',
  corriger: 'Corriger ce pointage',
  regulariser: 'Régulariser un fait manquant',
  annuler: 'Annuler ce pointage',
  verifier: 'Vérifier le journal',
  modifierFait: 'Consulter ou modifier le fait proposé',
  cloture: 'Clôturé',
  ouvert: 'Ouvert',
  continuation: 'Autres conflits du suivi',
  apercuRestant: 'Après cet acte : conflit restant',
  etats: {
    A_RESOUDRE: 'À résoudre',
    EN_COURS: 'En cours',
    TERMINEE: 'Terminée',
    ANNULEE: 'Annulée',
    REMPLACEE: 'Remplacée',
    ECHUE: 'Échue',
  },
  actes: {
    CORRECTION: 'Correction du pointage',
    ANNULATION: 'Annulation du pointage',
    REGULARISATION: 'Régularisation d’un fait manquant',
  },
  type: 'Type du pointage',
  intention: 'Intention réelle',
  identiteOperateur: 'Identifiant de l’opérateur concerné',
  identitePoste: 'Identifiant du poste (facultatif)',
  instant: 'Date et heure du fait',
  instantAide: 'Format ISO avec fuseau, par exemple 2026-09-14T17:00:00+02:00. Les fractions de seconde sont conservées.',
  incidentsTitre: 'Rejouer un incident de démonstration',
  incidentsAide: 'L’incident choisi affectera la prochaine opération concernée, dans cette session.',
  incidentArme: 'Incident prêt :',
  incidents: {
    PANNE_LECTURE: 'Lecture indisponible',
    PANNE_APERCU: 'Aperçu indisponible',
    PANNE_CONFIRMATION: 'Échec avant écriture',
    CONCURRENCE: 'Modification concurrente',
    ISSUE_INCONNUE: 'Réponse perdue après écriture',
    LECTURE_PARTIELLE: 'Acquisition partielle',
  },
  motif: 'Motif de la correction ou de l’annulation',
  motifAide: 'Obligatoire, 255 caractères au maximum.',
  previsualiser: 'Vérifier les conséquences',
  confirmer: 'Enregistrer cette décision',
  apercu: 'Vérifier avant d’enregistrer',
  comparerJournal: 'Comparer tous les pointages avant et après',
  apercuResolu: 'Conflit résolu après enregistrement de cette décision.',
  avant: 'Avant',
  apres: 'Après cet acte',
  restant: 'Acte enregistré, conflit restant',
  resolu: 'Conflit résolu',
  annule: 'Pointage annulé',
  remplace: 'Remplace le pointage',
  regularisation: 'Régularisation',
  droits: 'La correction est réservée aux gestionnaires. Vous pouvez consulter les faits.',
  erreurLecture: 'Le dossier n’a pas pu être chargé.',
  reessayer: 'Réessayer',
  adresseInvalide: 'L’adresse doit préciser un suivi et un pointage.',
  absences: {
    INTROUVABLE: 'Ce pointage est introuvable dans ce suivi.',
    ANCRE_ANNULEE: 'Le pointage de cette adresse a été annulé ou remplacé.',
    HORS_CONFLIT: 'Ce pointage ne relève plus d’un conflit.',
  },
  operation: {
    REPOS: '',
    PREVISUALISATION: 'Prévisualisation en cours…',
    CONFIRMATION: 'Enregistrement en cours…',
    CONCURRENCE: 'Ce suivi a changé. Le dossier est relu ; prévisualisez à nouveau votre décision.',
    ISSUE_INCONNUE: 'L’issue de l’écriture est inconnue. Vérifiez le journal avant toute nouvelle décision.',
    ERREUR: 'L’opération a échoué. Votre saisie est conservée.',
    REFUS: 'Acte refusé',
    LIMITATION: 'Limitation de la démonstration',
    APPLIQUE: 'Acte enregistré',
  },
  erreurs: ERREURS_SAISIE,
  retour: 'Retour aux conflits',
  dossier: 'Dossier de conflit',
  chronologie: 'Pointages et rattachements',
  cible: 'Vise l’activité',
  creee: 'Crée l’activité',
  enregistrement: 'Enregistré le',
  activites: 'Activités concernées',
  decision: 'Votre décision',
  choisir:
    'Choisissez ce qui correspond aux faits vérifiés. Ce choix prépare une correction ; vous vérifierez ses conséquences avant de l’enregistrer.',
  types: { DEBUT: 'Travail', NON_CONFORMITE: 'Non-conformité', FIN: 'Fin' },
  intentions: { OUVERTURE: 'Ouverture', TRANSITION: 'Transition', FIN: 'Fin ciblée' },
  titre: 'Conflits de pointage',
  sousTitre: 'Comprendre les faits, choisir une correction et vérifier ses conséquences avant de l’enregistrer.',
  donneesFictives: 'Démonstration · données fictives.',
  demonstration: 'Démonstration · données fictives, conservées pendant cette session. Un rechargement restaure les scénarios initiaux.',
  chargement: 'Chargement des conflits…',
  ouvrir: 'Examiner le dossier',
  element: 'Élément',
  operateur: 'Opérateur',
  poste: 'Poste',
  sansPoste: 'Sans poste',
  faits: 'Faits',
  diagnostic: 'Contradiction',
} as const;
