const ERREURS_SAISIE: Readonly<Record<string, string>> = {
  ACTE_REQUIS: 'Choisissez un acte.',
  MOTIF_REQUIS: 'Renseignez un motif.',
  MOTIF_INVALIDE: 'Le motif doit contenir de 1 à 255 caractères.',
  OPERATEUR_REQUIS: 'Renseignez l’opérateur.',
  CIBLE_REQUISE: 'Choisissez l’activité visée.',
  CIBLE_INTERDITE: 'Une ouverture ne vise aucune activité ; effacez explicitement la cible.',
  INSTANT_INVALIDE: 'Renseignez la date et l’heure du fait.',
  INTENTION_INCOMPATIBLE: 'Le type et l’intention ne sont pas compatibles.',
  TYPE_REQUIS: 'Choisissez le type du pointage.',
  INTENTION_REQUISE: 'Choisissez son intention.',
};

export const LIBELLES_ANOMALIES = {
  detail: 'Un pointage manque dans la chronologie ?',
  pourquoi: 'Pourquoi ces pointages sont incohérents',
  finAutomatique: 'Fin automatique',
  finAutomatiqueExplication:
    'Aucune fin réelle n’a terminé cette activité : elle a été terminée automatiquement à son échéance. Indiquez l’heure réelle de fin ou corrigez le pointage tardif.',
  debut: 'Début',
  finAutomatiqueA: 'Fin automatique',
  duree: 'Durée',
  tracabilite: 'Voir les détails et l’enregistrement',
  corriger: 'Corriger ce pointage',
  regulariser: 'Régulariser un fait manquant',
  annuler: 'Annuler ce pointage',
  verifier: 'Vérifier le reçu de confirmation',
  reprendreConfirmation: 'Reprendre la même confirmation',
  modifierFait: 'Consulter ou modifier le fait proposé',
  cloture: 'Clôturé',
  ouvert: 'Ouvert',
  continuation: 'Autres conflits du suivi',
  apercuRestant: 'Après cet acte : anomalie restante',
  etats: {
    A_RESOUDRE: 'À résoudre',
    EN_COURS: 'En cours',
    TERMINEE: 'Terminée',
    ANNULEE: 'Annulée',
    REMPLACEE: 'Remplacée',
    ECHUE: 'Échue',
  },
  actes: {
    CORRECTION: 'Correction du pointage',
    ANNULATION: 'Annulation du pointage',
    REGULARISATION: 'Régularisation d’un fait manquant',
  },
  type: 'Type du pointage',
  intention: 'Intention réelle',
  identiteOperateur: 'Identifiant de l’opérateur concerné',
  identitePoste: 'Identifiant du poste (facultatif)',
  champInstant: {
    legend: 'Date et heure du fait',
    date: 'Date',
    datePlaceholder: 'JJ/MM/AAAA',
    time: 'Heure',
    timePlaceholder: 'HH:MM:SS',
    openTimeList: 'Ouvrir la liste des heures',
    timeList: 'Heures proposées',
    skippedHour: 'Cette heure n’existe pas ce jour-là, à cause du changement d’heure.',
  },
  motif: 'Motif de la correction ou de l’annulation',
  motifAide: 'Obligatoire, 255 caractères au maximum.',
  previsualiser: 'Vérifier les conséquences',
  confirmer: 'Enregistrer cette décision',
  apercu: 'Vérifier avant d’enregistrer',
  comparerJournal: 'Comparer tous les pointages avant et après',
  apercuResolu: 'Anomalie traitée après enregistrement de cette décision.',
  avant: 'Avant',
  apres: 'Après cet acte',
  restant: 'Acte enregistré, anomalie restante',
  resolu: 'Anomalie traitée',
  annule: 'Pointage annulé',
  remplace: 'Remplace le pointage',
  regularisation: 'Régularisation',
  droits: 'La correction est réservée aux gestionnaires. Vous pouvez consulter les faits.',
  erreurLecture: 'Le dossier n’a pas pu être chargé.',
  reessayer: 'Réessayer',
  adresseInvalide: 'L’adresse doit préciser un suivi et un pointage.',
  absences: {
    INTROUVABLE: 'Ce pointage est introuvable dans ce suivi.',
    ANCRE_ANNULEE: 'Le pointage de cette adresse a été annulé ou remplacé.',
    SANS_ANOMALIE: 'Ce pointage ne relève plus d’une anomalie.',
  },
  operation: {
    REPOS: '',
    PREVISUALISATION: 'Prévisualisation en cours…',
    CONFIRMATION: 'Enregistrement en cours…',
    CONCURRENCE: 'Les données ont changé. Vérifiez un nouvel aperçu avant de confirmer.',
    ISSUE_INCONNUE: 'L’issue de l’écriture est inconnue. Vérifiez le journal avant toute nouvelle décision.',
    ERREUR: 'L’opération a échoué. Votre saisie est conservée.',
    REFUS: 'Acte refusé',
    APPLIQUE: 'Acte enregistré',
  },
  erreurs: ERREURS_SAISIE,
  retour: 'Retour aux anomalies',
  dossier: 'Dossier d’anomalie de pointage',
  chargementDossier: 'Chargement du dossier…',
  chronologie: 'Pointages et rattachements',
  cible: 'Vise l’activité',
  creee: 'Crée l’activité',
  enregistrement: 'Enregistré le',
  activites: 'Activités concernées',
  decision: 'Votre décision',
  choisir:
    'Choisissez ce qui correspond aux faits vérifiés. Ce choix prépare un acte ; vous vérifierez ses conséquences avant de l’enregistrer.',
  choix: {
    ANNULER_TRANSITION: {
      libelle: 'Annuler la transition',
      explication: 'Le pointage restera dans le journal avec votre motif d’annulation. Vérifiez ses conséquences dans l’aperçu.',
    },
    RATTACHER_FIN_A_ACTIVITE_REMPLACANTE: {
      libelle: 'Rattacher la fin à l’activité remplaçante',
      explication: 'La fin proposée visera l’activité indiquée dans les faits. Renseignez un motif, puis vérifiez l’aperçu.',
    },
    REGULARISER_FIN: {
      libelle: 'Régulariser la fin',
      explication: 'Aucune heure n’est proposée : saisissez l’heure réelle de fin, puis vérifiez l’aperçu avant d’enregistrer.',
    },
    CORRIGER_FIN_TARDIVE: {
      libelle: 'Corriger la fin pointée après l’échéance',
      explication: 'La fin pointée après l’échéance est reprise avec son heure. Renseignez un motif, puis vérifiez l’aperçu.',
    },
    CORRIGER_TRANSITION_TARDIVE: {
      libelle: 'Corriger la transition pointée après l’échéance',
      explication: 'La transition pointée après l’échéance est reprise avec son heure. Renseignez un motif, puis vérifiez l’aperçu.',
    },
  },
  types: { DEBUT: 'Travail', NON_CONFORMITE: 'Non-conformité', FIN: 'Fin' },
  intentions: { OUVERTURE: 'Ouverture', TRANSITION: 'Transition', FIN: 'Fin ciblée' },
  titre: 'Anomalies de pointage',
  sousTitre: 'Comprendre les faits, choisir une correction et vérifier ses conséquences avant de l’enregistrer.',
  ouvrir: 'Examiner le dossier',
  element: 'Élément',
  operateur: 'Opérateur',
  poste: 'Poste',
  sansPoste: 'Sans poste',
  operateurNonResolu: 'Opérateur non résolu',
  posteNonResolu: 'Poste non résolu',
  faits: 'Faits',
  diagnostic: 'Contradiction',
  raisons: {
    CIBLE_REMPLACEE: 'remplacée',
    CIBLE_DEJA_TERMINEE: 'déjà terminée',
    GESTE_AVANT_OUVERTURE: 'non encore ouverte à l’instant du geste',
    OUVRANT_ANNULE: 'dont le pointage d’ouverture est annulé',
    TRANSITION_MEME_CATEGORIE: 'dans une transition de même catégorie',
    CIBLE_ECHUE_AVEC_AUTRE_ACTIVITE: 'échue avec une autre activité présente',
    CONTRADICTION_REGULARISATION: 'dans une contradiction de régularisation',
  },
  diagnosticPointage: 'Le pointage',
  diagnosticCible: 'vise l’activité',
  diagnosticOuvrant: 'Ouverte par',
  diagnosticTerminaison: 'Terminée par',
} as const;
